* Exception: NotADirectoryError building Hardknott
@ 2021-07-18  4:01 Simon Haines
  2021-07-18 15:17 ` [yocto] " Richard Purdie
  0 siblings, 1 reply; 3+ messages in thread
From: Simon Haines @ 2021-07-18  4:01 UTC (permalink / raw)
  To: yocto


[-- Attachment #1.1: Type: text/plain, Size: 1102 bytes --]

I can't seem to find any information about this error, but I keep getting
variations of this when building hardknott:

Exception: NotADirectoryError: [Errno 20] Not a directory:
'/home/yocto/rpi64/build/tmp/sysroots-components/x86_64/gmp-native/usr/lib/pkgconfig/gmpxx.pc'
->
'/home/yocto/rpi64/build/tmp/work/x86_64-linux/libmpc-native/1.2.1-r0/recipe-sysroot-native/usr/lib/pkgconfig/gmpxx.pc'

I'm building in a container, and I've tried building the tip of the
hardknott branch, the hardknott-3.3.1 tag, and the release tarball (
http://downloads.yoctoproject.org/releases/yocto/yocto-3.3/poky-hardknott-25.0.0.tar.bz2).
All fail with the NotADirectory exception in different recipes. I've
attached logs from building the hardknott-3.3.1 tag and from the release
tarball.

The additional layers I'm using are (cloned from the tip of their
respective hardknott branches):
meta-openembedded
meta-raspberrypi
meta-security

It must be something with my setup because I've searched everywhere for
this issue and I can't find anything. Does this sound familiar to anyone?
Simon.

[-- Attachment #1.2: Type: text/html, Size: 1438 bytes --]

[-- Attachment #2: hardknott-3.3.1-log.do_unpack.386192 --]
[-- Type: application/octet-stream, Size: 1834 bytes --]

DEBUG: Executing python function extend_recipe_sysroot
NOTE: Direct dependencies are ['virtual:native:/home/yocto/poky-hardknott/meta/recipes-extended/xz/xz_5.2.5.bb:do_populate_sysroot']
ERROR: Error executing a python function in exec_python_func() autogenerated:

The stack trace of python calls that resulted in this exception/failure was:
File: 'exec_python_func() autogenerated', lineno: 2, function: <module>
     0001:
 *** 0002:extend_recipe_sysroot(d)
     0003:
File: '/home/yocto/poky-hardknott/meta/classes/staging.bbclass', lineno: 582, function: extend_recipe_sysroot
     0578:                    if "/bin/" in l or "/sbin/" in l:
     0579:                        # defer /*bin/* files until last in case they need libs
     0580:                        binfiles[l] = (targetdir, dest)
     0581:                    else:
 *** 0582:                        staging_copyfile(l, targetdir, dest, postinsts, seendirs)
     0583:
     0584:    # Handle deferred binfiles
     0585:    for l in binfiles:
     0586:        (targetdir, dest) = binfiles[l]
File: '/home/yocto/poky-hardknott/meta/classes/staging.bbclass', lineno: 157, function: staging_copyfile
     0153:        os.symlink(linkto, dest)
     0154:        #bb.warn(c)
     0155:    else:
     0156:        try:
 *** 0157:            os.link(c, dest)
     0158:        except OSError as err:
     0159:            if err.errno == errno.EXDEV:
     0160:                bb.utils.copyfile(c, dest)
     0161:            else:
Exception: NotADirectoryError: [Errno 20] Not a directory: '/home/yocto/rpi64/build/tmp/sysroots-components/x86_64/xz-native/usr/lib/pkgconfig/liblzma.pc' -> '/home/yocto/rpi64/build/tmp/work/x86_64-linux/unifdef-native/2.12-r0/recipe-sysroot-native/usr/lib/pkgconfig/liblzma.pc'

DEBUG: Python function extend_recipe_sysroot finished

[-- Attachment #3: release-tarball-log.do_prepare_recipe_sysroot.27932 --]
[-- Type: application/octet-stream, Size: 2559 bytes --]

DEBUG: Executing python function do_prepare_recipe_sysroot
DEBUG: Executing python function extend_recipe_sysroot
NOTE: Direct dependencies are ['virtual:native:/home/yocto/poky-hardknott-25.0.0/meta/recipes-devtools/automake/automake_1.16.3.bb:do_populate_sysroot', '/home/yocto/poky-hardknott-25.0.0/meta/recipes-extended/texinfo-dummy-native/texinfo-dummy-native.bb:do_populate_sysroot', '/home/yocto/poky-hardknott-25.0.0/meta/recipes-devtools/libtool/libtool-native_2.4.6.bb:do_populate_sysroot', 'virtual:native:/home/yocto/poky-hardknott-25.0.0/meta/recipes-devtools/autoconf/autoconf_2.71.bb:do_populate_sysroot', 'virtual:native:/home/yocto/poky-hardknott-25.0.0/meta/recipes-support/gmp/gmp_6.2.1.bb:do_populate_sysroot', 'virtual:native:/home/yocto/poky-hardknott-25.0.0/meta/recipes-support/mpfr/mpfr_4.1.0.bb:do_populate_sysroot']
ERROR: Error executing a python function in exec_python_func() autogenerated:

The stack trace of python calls that resulted in this exception/failure was:
File: 'exec_python_func() autogenerated', lineno: 2, function: <module>
     0001:
 *** 0002:extend_recipe_sysroot(d)
     0003:
File: '/home/yocto/poky-hardknott-25.0.0/meta/classes/staging.bbclass', lineno: 582, function: extend_recipe_sysroot
     0578:                    if "/bin/" in l or "/sbin/" in l:
     0579:                        # defer /*bin/* files until last in case they need libs
     0580:                        binfiles[l] = (targetdir, dest)
     0581:                    else:
 *** 0582:                        staging_copyfile(l, targetdir, dest, postinsts, seendirs)
     0583:
     0584:    # Handle deferred binfiles
     0585:    for l in binfiles:
     0586:        (targetdir, dest) = binfiles[l]
File: '/home/yocto/poky-hardknott-25.0.0/meta/classes/staging.bbclass', lineno: 157, function: staging_copyfile
     0153:        os.symlink(linkto, dest)
     0154:        #bb.warn(c)
     0155:    else:
     0156:        try:
 *** 0157:            os.link(c, dest)
     0158:        except OSError as err:
     0159:            if err.errno == errno.EXDEV:
     0160:                bb.utils.copyfile(c, dest)
     0161:            else:
Exception: NotADirectoryError: [Errno 20] Not a directory: '/home/yocto/rpi64/build/tmp/sysroots-components/x86_64/gmp-native/usr/lib/pkgconfig/gmpxx.pc' -> '/home/yocto/rpi64/build/tmp/work/x86_64-linux/libmpc-native/1.2.1-r0/recipe-sysroot-native/usr/lib/pkgconfig/gmpxx.pc'

DEBUG: Python function extend_recipe_sysroot finished
DEBUG: Python function do_prepare_recipe_sysroot finished

^ permalink raw reply	[flat|nested] 3+ messages in thread
* Re: [yocto] Exception: NotADirectoryError building Hardknott
  2021-07-18  4:01 Exception: NotADirectoryError building Hardknott Simon Haines
@ 2021-07-18 15:17 ` Richard Purdie
  2021-07-20  7:52   ` Simon Haines
  0 siblings, 1 reply; 3+ messages in thread
From: Richard Purdie @ 2021-07-18 15:17 UTC (permalink / raw)
  To: Simon Haines, yocto

On Sun, 2021-07-18 at 14:01 +1000, Simon Haines wrote:
> I can't seem to find any information about this error, but I keep getting variations of this when building
> hardknott:
> 
> Exception: NotADirectoryError: [Errno 20] Not a directory: '/home/yocto/rpi64/build/tmp/sysroots-
> components/x86_64/gmp-native/usr/lib/pkgconfig/gmpxx.pc' -> '/home/yocto/rpi64/build/tmp/work/x86_64-
> linux/libmpc-native/1.2.1-r0/recipe-sysroot-native/usr/lib/pkgconfig/gmpxx.pc'
> 
> I'm building in a container, and I've tried building the tip of the hardknott branch, the hardknott-3.3.1
> tag, and the release tarball (
> http://downloads.yoctoproject.org/releases/yocto/yocto-3.3/poky-hardknott-25.0.0.tar.bz2). All fail with the
> NotADirectory exception in different recipes. I've attached logs from building the hardknott-3.3.1 tag and
> from the release tarball.
> 
> The additional layers I'm using are (cloned from the tip of their respective hardknott branches):
> meta-openembedded
> meta-raspberrypi
> meta-security
> 
> It must be something with my setup because I've searched everywhere for this issue and I can't find
> anything. Does this sound familiar to anyone?

How is your container filesystem setup/configured? It looks like the filesystem
isn't liking the build trying to create hardlinked files. It is odd it would
get as far as gmp-native before having problems. That file definitely isn't a
directory too, it is an odd error.

I'd suspect it is something like the copy-on-write mode of the filesystem
having issues.

Cheers,

Richard


^ permalink raw reply	[flat|nested] 3+ messages in thread
* Re: [yocto] Exception: NotADirectoryError building Hardknott
  2021-07-18 15:17 ` [yocto] " Richard Purdie
@ 2021-07-20  7:52   ` Simon Haines
  0 siblings, 0 replies; 3+ messages in thread
From: Simon Haines @ 2021-07-20  7:52 UTC (permalink / raw)
  To: Richard Purdie; +Cc: yocto

[-- Attachment #1: Type: text/plain, Size: 754 bytes --]

On Mon, 19 Jul 2021 at 01:17, Richard Purdie <
richard.purdie@linuxfoundation.org> wrote:

> How is your container filesystem setup/configured? It looks like the
> filesystem
> isn't liking the build trying to create hardlinked files. It is odd it
> would
> get as far as gmp-native before having problems. That file definitely
> isn't a
> directory too, it is an odd error.
>
>
Thanks Richard, I suspect you're right. I'm using fuse-overlayfs which I'm
mounting with the 'noxattrs' option because the host is Fedora and its
SELinux configuration interferes with yocto in other ways. It looks like
overlayfs uses xattrs in some cases for hard link resolution. I'll have to
dig in deeper there, thanks for the pointer.

Cheers,
Simon.

[-- Attachment #2: Type: text/html, Size: 1192 bytes --]

^ permalink raw reply	[flat|nested] 3+ messages in thread
end of thread, other threads:[~2021-07-20  7:52 UTC | newest]

Thread overview: 3+ messages (download: mbox.gz / follow: Atom feed)
-- links below jump to the message on this page --
2021-07-18  4:01 Exception: NotADirectoryError building Hardknott Simon Haines
2021-07-18 15:17 ` [yocto] " Richard Purdie
2021-07-20  7:52   ` Simon Haines

