* run.do_image_zipabox2_sdimg.27223: parted: not found
@ 2021-07-01 15:57 Yocto
  2021-07-01 16:43 ` [yocto] " Zoran
  0 siblings, 1 reply; 2+ messages in thread
From: Yocto @ 2021-07-01 15:57 UTC (permalink / raw)
  To: yocto

[-- Attachment #1: Type: text/plain, Size: 2711 bytes --]

having a really funky issue
everything builds fine under pyro

updated it all to dunfell, and now im hitting this failure below, i also 
pasted the log and the offending recipe on pastebin 
logfile: https://pastebin.com/38TzNa5h

bb recipe: https://pastebin.com/jhfTBv58

Logfile of failure stored in: 
/home/dingo/TEST3/Zipato/zipato-yocto-public/build/tmp/work/zipabox2-poky-linux-gnueabi/zipabox2-image-blank/1.0-r0/temp/log.do_image_zipabox2_sdimg.27223


Log data follows:
| DEBUG: Executing python function set_image_size
| DEBUG: 1032444.400000 = 794188 * 1.300000
| DEBUG: 1032444.400000 = max(1032444.400000, 8192)[1032444.400000] + 0
| DEBUG: 1032445.000000 = int(1032444.400000)
| DEBUG: 1032445 = aligned(1032445)
| DEBUG: returning 1032445
| DEBUG: Python function set_image_size finished
| DEBUG: Executing shell function do_image_zipabox2_sdimg
| 0+0 records in
| 0+0 records out
| 0 bytes copied, 8.9773e-05 s, 0.0 kB/s
| 
/home/dingo/TEST3/Zipato/zipato-yocto-public/build/tmp/work/zipabox2-poky-linux-gnueabi/zipabox2-image-blank/1.0-r0/temp/run.do_image_zipabox2_sdimg.27223: 
124: 
/home/dingo/TEST3/Zipato/zipato-yocto-public/build/tmp/work/zipabox2-poky-linux-gnueabi/zipabox2-image-blank/1.0-r0/temp/run.do_image_zipabox2_sdimg.27223: 
parted: not found
| WARNING: exit code 127 from a shell command.
| ERROR: Execution of 
'/home/dingo/TEST3/Zipato/zipato-yocto-public/build/tmp/work/zipabox2-poky-linux-gnueabi/zipabox2-image-blank/1.0-r0/temp/run.do_image_zipabox2_sdimg.27223' 
failed with exit code 127:
| 0+0 records in
| 0+0 records out
| 0 bytes copied, 8.9773e-05 s, 0.0 kB/s
| 
/home/dingo/TEST3/Zipato/zipato-yocto-public/build/tmp/work/zipabox2-poky-linux-gnueabi/zipabox2-image-blank/1.0-r0/temp/run.do_image_zipabox2_sdimg.27223: 
124: 
/home/dingo/TEST3/Zipato/zipato-yocto-public/build/tmp/work/zipabox2-poky-linux-gnueabi/zipabox2-image-blank/1.0-r0/temp/run.do_image_zipabox2_sdimg.27223: 
parted: not found
| WARNING: exit code 127 from a shell command.
| ERROR: Task 
(/home/dingo/TEST3/Zipato/zipato-yocto-public/meta-zipato-public/images/zipabox2-image/zipabox2-image-blank_1.0.bb:do_image_zipabox2_sdimg) 
failed with exit code '1'
NOTE: Tasks Summary: Attempted 4542 tasks of which 4540 didn't need to be 
rerun and 2 failed.

Summary: 2 tasks failed:
   
/home/dingo/TEST3/Zipato/zipato-yocto-public/meta-zipato-public/images/zipabox2-image/zipabox2-image-blank_1.0.bb:do_image_zipabox2_mender
   
/home/dingo/TEST3/Zipato/zipato-yocto-public/meta-zipato-public/images/zipabox2-image/zipabox2-image-blank_1.0.bb:do_image_zipabox2_sdimg

-- 
Sent with Vivaldi Mail. Download Vivaldi for free at vivaldi.com

[-- Attachment #2: Type: text/html, Size: 3435 bytes --]

^ permalink raw reply	[flat|nested] 2+ messages in thread
* Re: [yocto] run.do_image_zipabox2_sdimg.27223: parted: not found
  2021-07-01 15:57 run.do_image_zipabox2_sdimg.27223: parted: not found Yocto
@ 2021-07-01 16:43 ` Zoran
  0 siblings, 0 replies; 2+ messages in thread
From: Zoran @ 2021-07-01 16:43 UTC (permalink / raw)
  To: Yocto; +Cc: Yocto-mailing-list

[-- Attachment #1: Type: text/plain, Size: 2912 bytes --]

having a really funky issue


This is the truth... Truly funky issue, no doubts! ðŸ’£

Zee
_______

On Thu, Jul 1, 2021 at 5:57 PM Yocto <yocto@optimcloud.com> wrote:

> having a really funky issue everything builds fine under pyro updated it
> all to dunfell, and now im hitting this failure below, i also pasted the
> log and the offending recipe on pastebin logfile:
> https://pastebin.com/38TzNa5h bb recipe: https://pastebin.com/jhfTBv58
> Logfile of failure stored in:
> /home/dingo/TEST3/Zipato/zipato-yocto-public/build/tmp/work/zipabox2-poky-linux-gnueabi/zipabox2-image-blank/1.0-r0/temp/log.do_image_zipabox2_sdimg.27223
> Log data follows: | DEBUG: Executing python function set_image_size |
> DEBUG: 1032444.400000 = 794188 * 1.300000 | DEBUG: 1032444.400000 =
> max(1032444.400000, 8192)[1032444.400000] + 0 | DEBUG: 1032445.000000 =
> int(1032444.400000) | DEBUG: 1032445 = aligned(1032445) | DEBUG: returning
> 1032445 | DEBUG: Python function set_image_size finished | DEBUG: Executing
> shell function do_image_zipabox2_sdimg | 0+0 records in | 0+0 records out |
> 0 bytes copied, 8.9773e-05 s, 0.0 kB/s |
> /home/dingo/TEST3/Zipato/zipato-yocto-public/build/tmp/work/zipabox2-poky-linux-gnueabi/zipabox2-image-blank/1.0-r0/temp/run.do_image_zipabox2_sdimg.27223:
> 124:
> /home/dingo/TEST3/Zipato/zipato-yocto-public/build/tmp/work/zipabox2-poky-linux-gnueabi/zipabox2-image-blank/1.0-r0/temp/run.do_image_zipabox2_sdimg.27223:
> parted: not found | WARNING: exit code 127 from a shell command. | ERROR:
> Execution of
> '/home/dingo/TEST3/Zipato/zipato-yocto-public/build/tmp/work/zipabox2-poky-linux-gnueabi/zipabox2-image-blank/1.0-r0/temp/run.do_image_zipabox2_sdimg.27223'
> failed with exit code 127: | 0+0 records in | 0+0 records out | 0 bytes
> copied, 8.9773e-05 s, 0.0 kB/s |
> /home/dingo/TEST3/Zipato/zipato-yocto-public/build/tmp/work/zipabox2-poky-linux-gnueabi/zipabox2-image-blank/1.0-r0/temp/run.do_image_zipabox2_sdimg.27223:
> 124:
> /home/dingo/TEST3/Zipato/zipato-yocto-public/build/tmp/work/zipabox2-poky-linux-gnueabi/zipabox2-image-blank/1.0-r0/temp/run.do_image_zipabox2_sdimg.27223:
> parted: not found | WARNING: exit code 127 from a shell command. | ERROR:
> Task
> (/home/dingo/TEST3/Zipato/zipato-yocto-public/meta-zipato-public/images/zipabox2-image/zipabox2-image-blank_1.0.bb:do_image_zipabox2_sdimg)
> failed with exit code '1' NOTE: Tasks Summary: Attempted 4542 tasks of
> which 4540 didn't need to be rerun and 2 failed. Summary: 2 tasks failed:
> /home/dingo/TEST3/Zipato/zipato-yocto-public/meta-zipato-public/images/zipabox2-image/zipabox2-image-blank_1.0.bb:do_image_zipabox2_mender
> /home/dingo/TEST3/Zipato/zipato-yocto-public/meta-zipato-public/images/zipabox2-image/zipabox2-image-blank_1.0.bb:do_image_zipabox2_sdimg
> --
> Sent with Vivaldi Mail. Download Vivaldi for free at vivaldi.com
>
> 
>
>

[-- Attachment #2: Type: text/html, Size: 5500 bytes --]

^ permalink raw reply	[flat|nested] 2+ messages in thread
end of thread, other threads:[~2021-07-01 16:43 UTC | newest]

Thread overview: 2+ messages (download: mbox.gz / follow: Atom feed)
-- links below jump to the message on this page --
2021-07-01 15:57 run.do_image_zipabox2_sdimg.27223: parted: not found Yocto
2021-07-01 16:43 ` [yocto] " Zoran

