* [yocto] Failing EXTERNALSRC and dangling symlinks
@ 2022-09-06  0:11 David Antliff
  0 siblings, 0 replies; only message in thread
From: David Antliff @ 2022-09-06  0:11 UTC (permalink / raw)
  To: yocto

Hi,

I don't know how to reply to list messages from a thread I wasn't subscribed to at the time, but I'd like to follow up on this thread from August 2016:

https://www.yoctoproject.org/pipermail/yocto/2016-August/031671.html

I can confirm that the referenced patch to checksum.py is part of my Yocto distribution (gatesgarth), yet I continue to see this issue with broken symlinks created by EXTERNALSRC rules.

WARNING: Unable to get checksum for my-recipe SRC_URI entry oe-workdir: [Errno 2] No such file or directory: '/.../my-recipe/oe-workdir'
WARNING: Unable to get checksum for my-recipe SRC_URI entry oe-logs: [Errno 2] No such file or directory: '/.../my-recipe/oe-logs'

As mentioned in the original message, this occurs when the symlinks created by EXTERNALSRC are broken by, say, a removal of the build directory.

It's not a big deal because it doesn't break the build, but the original thread was left hanging, so I hope this info helps.

-- David.


^ permalink raw reply	[flat|nested] only message in thread
only message in thread, other threads:[~2022-09-06  0:11 UTC | newest]

Thread overview: (only message) (download: mbox.gz / follow: Atom feed)
-- links below jump to the message on this page --
2022-09-06  0:11 [yocto] Failing EXTERNALSRC and dangling symlinks David Antliff

